import { ItemsProps } from "./gloabal";
import {
  faMessage,
  faEllipsis,
  faSquarePollHorizontal,
  faSliders,
  faImage,
  faEnvelope,
  faCode,
  faCloudArrowUp,
  faCloudArrowDown,
} from "@fortawesome/free-solid-svg-icons";

const defaultOpacity = 0.3;
const defaultPosition = [0, 0];
const Items: ItemsProps[] = [
  {
    Logo: faMessage,
    Name: "Send a Message",
    Description: 'Send a message to user e.g "Hi"',
    OutPort: 1,
    bgColor: "green",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faEllipsis,
    Name: "Ask Question withoptions",
    Description: "E.g Ask gender",
    OutPort: 2,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faSquarePollHorizontal,
    Name: "Ask Question with input",
    Description: "E.g Ask Name",
    OutPort: 1,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["true","false"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faSliders,
    Name: "Conditional Jumps",
    Description: "E.g Address as Mr. if gender is male",
    OutPort: 2,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faImage,
    Name: "Send a Picture",
    Description: "E.g a product photo or simply a GIF",
    OutPort: 1,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faEnvelope,
    Name: "Recive Email",
    Description: "Get e-mail of the responses collected.",
    OutPort: 1,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faCode,
    Name: "Script Block",
    Description: "Meant for developers.",
    OutPort: 1,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faCloudArrowUp,
    Name: "Get API",
    Description: "Get data from an API/URL",
    OutPort: 1,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
  {
    Logo: faCloudArrowDown,
    Name: "Post API",
    Description: "Post data to an API/URL",
    OutPort: 1,
    bgColor: "",
    schema: {
      position: defaultPosition,
      OutputPort: ["next"],
      Inport: 1,
      connection: [],
      opacity: defaultOpacity,
      exist: false,
      Name: "Message",
      Message: "hi",
    },
  },
];

export default Items;
